### ISSUE TITLE
Cant use Ed

### ISSUE THREAD

**Issue by Macta3** [nrootconauto/Aiwnios#12]
I was trying to make a new .HC file. For some reason it gives an Undefined identifier at "Ed" error.

**Comment by nrootconauto** [comment]
Oh,what Operating system(Windows/Linux/Mac) and if you know what architecture. Run `git checkout -- .` in the main folder if you have made any edits to the source code(happens when browsing through src sometimes).

Ill try my best to fix it. Sometimes when typeing stuff,garbage from the previous line gets interpreted with the next line. HolyC doesnt do line by line things.

**Comment by nrootconauto** [comment]
Ill give an example of what I mean
![image](https://github.com/user-attachments/assets/ed96c8eb-dbdd-48fb-9eb8-9b2d2d6e42be)

**Comment by Macta3** [comment]
I am using Ubuntu. Since my windows 11 didnt work I thought that the ubuntu would. which it did.

**Comment by nrootconauto** [comment]
Can I see a screenshot of the Ed failure. Also,I will get onto the windows 11 bug. What is your PC build. I plan on buying parts soon

**Comment by Macta3** [comment]
Well it started working. I don't know what caused it to mess up like that when I was trying it. Also for the Windows 11 thing it is an HP EliteBook 640 G11 with an Intel Core Ultra 5 135U 12/14. 32 gigs of ddr5 ram.

**Comment by juicedupjoe** [comment]
>Since my windows 11 didnt work I thought that the ubuntu would.
Can you elaborate? Did it not build or not run? Can you attach a screenshot of it not working?

**Comment by nrootconauto** [comment]
Thanks,I have about $1000 dollars to spare. Im serious about the windows 11 issue.

**Comment by Macta3** [comment]
Well when i did it last time it would build but when i would try to run it it would crash. I tried to reinstall it but for some reason Mingw64 cant find the SDL2 libraries.
